name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean test

    - name: Generate Allure report
      run: mvn allure:report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results